%write data to ASCII files


[file,path] = uiputfile('*.csv','Save dive analysis to file');

resname = [path file];
dive = [];
tripStats = [];
%&resname=['DiveAnalysis_' date];

[fiddive,msg]=fopen(resname,'wt');
fprintf(fiddive,[ 'birdID', '\t',...
                  'TripNumber','\t',...
                  'EventNo', '\t',...
                  'Date', '\t',...
                  'SurfaceTime', '\t',...
                  'NoFixes', '\t',...
                  'FirstLat', '\t',...
                  'FirstLon', '\t',...
                  'LastLat', '\t',...
                  'LastLon', '\t',...
                   'SurfaceDist', '\t',...
                   'SurfaceVelo', '\t',...
                   'EvtOnset', '\t',...
                   'EvtEnd', '\t',...
                   'DiveTime', '\t',...
                   'DiveDistance', '\t',...
                   'EvtMaxDepth', '\t',...
                   'DescDur', '\t',...
                   'DescVelo', '\t',...
                   'StartBot', '\t',...
                   'NoWiggles', '\t',...
                   'MeanWigAmp', '\t',...
                   'MaxWigAmp', '\t',...
                   'BottomTime', '\t',...
                   'BottomEnd', '\t',...
                   'AscDur', '\t',...
                   'AscVelo', '\t',...
                   'Diving Efficiency', '\t',...
                   'Foraging Efficiency', '\t',...
                   'Lat', '\t',...
                   'Lon', '\t',...
                   'ExpolLat', '\t',...
                   'ExpolLon', '\t',...
                   'ExpolTTF', '\t',...
                   'ExpolGap', '\t',...
                   'Homerange', '\t',...
                   'Cumulative Distance', '\t',...
                   'Segment speed\n']);
% [fidstats,msg]=fopen(['statsEtxt'],'wt');
% fprintf(fidstats,[ 'birdID\tday\tn\tsurface time\t'...
%         'surface dist\tsurface speed\tdive time\tdive dist\tmax depth\tdesc dur\tdesc rate\tstart bot\tno wiggles\t'...
%         'mean w amp\tmin\tmax\tmean w speed\tmin\tmax\tbottom dur\tend bot\tasc dur\tasc velo\ttop temp\t'...
%         'top temp sd\ttop temp n\tbot temp\tbot temp sd\tbot temp n\tdiving efficiency\tforaging effort\n']);
% [fidhstats,msg]=fopen(['hstats.txt'],'wt');
% fprintf(fidhstats,[ 'birdID\tday\thh:mm\thrs\tn\tsurface time\t'...
%         'surface dist\tsurface speed\tdive time\tdive dist\tmax depth\tdesc dur\tdesc rate\tstart bot\tno wiggles\t'...
%         'mean w amp\tmin\tmax\tmean w speed\tmin\tmax\tbottom dur\tend bot\tasc dur\tasc velo\ttop temp\t'...
%         'top temp sd\ttop temp n\tbot temp\tbot temp sd\tbot temp n\tdiving efficiency\tforaging effort\n']);
for r=1:size(DiveData,2)
    
    birdID=DiveData(r).birdID;
    dtemp=size(DiveData(r).dive.TripNumber,1);
%     stemp=DiveData(r).tripStats;
%     htemp=DiveData(r).hourStats;
    
    %print dive data
    for d=1:dtemp
        fprintf(fiddive,[ birdID, '\t',...
                          num2str(DiveData(r).dive.TripNumber(d)), '\t',...
                          num2str(DiveData(r).dive.EventNo(d)), '\t',...  
                          DiveData(r).dive.Date(d,:), '\t',...
                          num2str(DiveData(r).dive.SurfaceTime(d)), '\t',...
                          num2str(DiveData(r).dive.NoFixes(d)), '\t', ...
                          num2str(DiveData(r).dive.FirstLat(d)), '\t', ...
                          num2str(DiveData(r).dive.FirstLon(d)), '\t', ...
                          num2str(DiveData(r).dive.LastLat(d)), '\t', ...
                          num2str(DiveData(r).dive.LastLon(d)), '\t', ...
                          num2str(DiveData(r).dive.SurfaceDist(d)), '\t',...
                          num2str(DiveData(r).dive.SurfaceVelo(d)), '\t',...
                          DiveData(r).dive.EvtOnset(d,:), '\t',...
                          DiveData(r).dive.EvtEnd(d,:), '\t',...
                          num2str(DiveData(r).dive.DiveTime(d)), '\t',...
                          num2str(DiveData(r).dive.DiveDistance(d)), '\t', ...
                          num2str(DiveData(r).dive.EvtMaxDepth(d)), '\t',...
                          num2str(DiveData(r).dive.DescDur(d)), '\t', ...
                          num2str(DiveData(r).dive.DescVelo(d)), '\t',...
                          num2str(DiveData(r).dive.StartBot(d)), '\t',...
                          num2str(DiveData(r).dive.NoWiggles(d)), '\t', ...
                          num2str(DiveData(r).dive.MeanWigAmp(d)), '\t',...
                          num2str(DiveData(r).dive.MaxWigAmp(d)), '\t',...
                          num2str(DiveData(r).dive.BottomTime(d)), '\t',...
                          num2str(DiveData(r).dive.BottomEnd(d)), '\t',...
                          num2str(DiveData(r).dive.AscDur(d)), '\t',...
                          num2str(DiveData(r).dive.AscVelo(d)), '\t',...
                          num2str(DiveData(r).dive.DivingEfficiency(d)), '\t',...
                          num2str(DiveData(r).dive.ForagingEfficiency(d)), '\t',...
                          num2str(DiveData(r).dive.Lat(d),8), '\t',...
                          num2str(DiveData(r).dive.Lon(d),8), '\t',...
                          num2str(DiveData(r).dive.ExpolLat(d),8), '\t',...
                          num2str(DiveData(r).dive.ExpolLon(d),8), '\t',...
                          num2str(DiveData(r).dive.ExpolTTF(d)), '\t',...
                          num2str(DiveData(r).dive.ExpolGap(d)), '\t',...
                          num2str(DiveData(r).dive.HomeRange(d)), '\t',...
                          num2str(DiveData(r).dive.CumulativeDistance(d)), '\t',...
                          num2str(DiveData(r).dive.SegmentSpeed(d)), '\n']);
    end
%     for d=1:size(stemp,1)
% 
%         fprintf(fidstats,[ birdID, '\t',  num2str(stemp(d,1)), '\t', num2str(stemp(d,2)), '\t',...  
%                 num2str(stemp(d,3)), '\t',num2str(stemp(d,4)), '\t', num2str(stemp(d,5)), '\t', ...
%                 num2str(stemp(d,6)), '\t', num2str(stemp(d,7)), '\t', num2str(stemp(d,8)), '\t', ...
%                 num2str(stemp(d,9)), '\t', num2str(stemp(d,10)), '\t', num2str(stemp(d,11)), '\t', ...
%                 num2str(stemp(d,12)), '\t', num2str(stemp(d,13)), '\t', num2str(stemp(d,14)), '\t', ...
%                 num2str(stemp(d,15)), '\t', num2str(stemp(d,16)), '\t', num2str(stemp(d,17)), '\t', ...
%                 num2str(stemp(d,18)), '\t', num2str(stemp(d,19)), '\t', num2str(stemp(d,20)), '\t', ...
%                 num2str(stemp(d,21)), '\t', num2str(stemp(d,22)), '\t', num2str(stemp(d,23)), '\t', ...
%                 num2str(stemp(d,24)), '\t', num2str(stemp(d,25)), '\t', num2str(stemp(d,26)), '\t', ...
%                 num2str(stemp(d,27)), '\t', num2str(stemp(d,28)), '\t', num2str(stemp(d,29)), '\t', num2str(stemp(d,30)), '\n']);
%     end
%     
%     for d=1:size(htemp,1)
%         if ~isnan(htemp(d,1))
%             tmp_hr=datestr(htemp(d,1),15);
%             tmp2_hr=tmp_hr(1:2);
%             tmp_day=datestr(htemp(d,1),19);
%         else
%             tmp_hr=' ';
%             tmp_day=' ';
%         end
%         fprintf(fidhstats,[ birdID, '\t',  tmp_day, '\t', tmp_hr, '\t', tmp2_hr, '\t', num2str(htemp(d,2)), '\t',...  
%                 num2str(htemp(d,3)), '\t',num2str(htemp(d,4)), '\t', num2str(htemp(d,5)), '\t', ...
%                 num2str(htemp(d,6)), '\t', num2str(htemp(d,7)), '\t', num2str(htemp(d,8)), '\t', ...
%                 num2str(htemp(d,9)), '\t', num2str(htemp(d,10)), '\t', num2str(htemp(d,11)), '\t', ...
%                 num2str(htemp(d,12)), '\t', num2str(htemp(d,13)), '\t', num2str(htemp(d,14)), '\t', ...
%                 num2str(htemp(d,15)), '\t', num2str(htemp(d,16)), '\t', num2str(htemp(d,17)), '\t', ...
%                 num2str(htemp(d,18)), '\t', num2str(htemp(d,19)), '\t', num2str(htemp(d,20)), '\t', ...
%                 num2str(htemp(d,21)), '\t', num2str(htemp(d,22)), '\t', num2str(htemp(d,23)), '\t', ...
%                 num2str(htemp(d,24)), '\t', num2str(htemp(d,25)), '\t', num2str(htemp(d,26)), '\t', ...
%                 num2str(htemp(d,27)), '\t', num2str(htemp(d,28)), '\t', num2str(htemp(d,29)), '\t', num2str(htemp(d,30)), '\n']);
%     end
    
end
fclose all;
clear all
    